export const Strings = {
  chooseYourRole: 'Choose Your Role',
  staff: 'Staff',
  manager: 'Manager',
  asm: 'ASM',
  staffDescription:
    'Track your sales and compare\nperformance with other staff.',
  branchOperation: 'Leads branch operations and\ndistributes targets to staff.',
  asmDescription:
    'Track and compare performance\nof all staff and branches in your\nregion',
  welcomeBack: 'Welcome Back',
  loginSubtitle: 'Login to access your performance workspace',
  login: 'Login',
  emailLabel: 'Email / #ID',
  emailPlaceholder: 'Enter email or #ID',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Enter password',
  pleaseEnterEmail: 'Please enter email',
  pleaseEnterValidEmail: 'Please enter a valid email',
  pleaseEnterPassword: 'Please enter password',
  forgotPassword: 'Forgot Password?',
  forgotPasswordHeader: 'Forgot Password',
  cannotLogin: 'Cannot log in?',
  forgotPasswordDesc:
    'Enter your email and we will send a verification code',
  forgotPasswordEmailLabel: 'Email',
  forgotPasswordEmailPlaceholder: 'Enter email',
  sendVerificationCode: 'Send Verification Code',
  createPasswordHeader: 'Create Password',
  setNewPassword: 'Set New Password',
  changePasswordHeader: 'Change Password',
  changePasswordTitle: 'Set New Password',
  passwordRulesDesc:
    '8-16 characters, lowercase/uppercase letters, digits and symbols with at least three kinds of them contained.',
  newPasswordLabel: 'New Password',
  newPasswordPlaceholder: 'New Password',
  confirmPasswordLabel: 'Confirm Password',
  confirmPasswordPlaceholder: 'Confirm Password',
  continue: 'Continue',
  verificationHeader: 'Verification',
  enterOtp: 'Enter OTP',
  otpSentTo: 'OTP sent to mail@gmail.com',
  didntReceiveCode: "I didn't receive a code. ",
  resend: 'Resend',
  surveyHeader: 'Survey',
  priceSatisfactionSurvey: 'Price Satisfaction Survey',
  surveyQuestionsCount: '2 Questions',
  q1: 'Q1',
  q2: 'Q2',
  surveyQuestion1: 'How do you rate our unstitched pricing?',
  surveyQuestion2: 'How do you rate our bags pricing?',
  optionHigh: 'High',
  optionFair: 'Fair',
  optionLow: 'Low',
  active: 'ACTIVE',
  openSurvey: 'Open Survey',
  surveySubmitted: 'Survey Submitted',
  submitSurvey: 'Submit Survey',
  feedbackHeader: 'Feedback',
  shareYourFeedback: 'Share Your Feedback',
  feedbackSubtitle: 'Help us improve by sharing your insights',
  codeLabel: 'Code',
  nameLabel: 'Name',
  branchLabel: 'Branch',
  yourFeedbackLabel: 'Your Feedback',
  required: 'Required',
  feedbackNote: 'Be specific about customer needs or product issues',
  submitFeedback: 'Submit Feedback',
  announcementHeader: 'Announcement',
  readMore: 'Read More',
  notificationHeader: 'Notifications',
  recent: 'Recent',
  unreadCount: '4 Unread',
  salesStaff: 'Sales Staff',
  branchManager: 'Branch Manager',
  branchManagerHomeBranch: 'Branch Manager - Branch',
  asmHomeBranch: 'ASM . Region Lahore',
  branchOverview: 'Branch Overview',
  regionalOverview: 'Regional Overview',
  branchIncentiveSub: 'Branch level incentive records',
  regionalIncentiveSub: 'Regional level incentive records',
  comparison: 'Comparison',
  staffComparison: 'Staff Comparison',
  branchComparison: 'Branch Comparison',
  asmGarments: 'Garments',
  asmUnstitched: 'Unstiched',
  asmAccessories: 'Accesories',
  achievementPercent: 'Achievement %',
  regionComparison: 'Region Comparison',
  salesStaffPerformance: 'Sales Staff Performance',
  viewTarget: 'View Target',
  surveysReport: 'Surveys Report',
  roleLabel: 'Role',
  customerServiceTraining: 'Customer Service Training',
  productTraining: 'Product Training',
  displayTraining: 'Display Training',
  announcements: 'Announcements',
  feedback: 'Feedback',
  surveys: 'Surveys',
  logout: 'Logout',
  home: 'Home',
  training: 'Training',
  alerts: 'Alerts',
  homeUserName: 'Employee Name',
  salerName: 'Saler Name',
  branchManagerName: 'Branch Manager Name',
  asmName: 'ASM Name',
  homeUserBranch: 'Sales Staff - Branch',
  myPerformance: 'My Performance',
  targetVsAchievement: 'Target vs Achievement',
  targetVsAchievementSub: 'Category wise progress and remaining gap',
  percentAchieved: '% Achieved',
  percentRemaining: '% Remaining',
  commission: 'Commission',
  commissionSub: 'Current progress',
  targetStat: 'Target',
  saleStat: 'Sale',
  commissionStat: 'Commission',
  categoryBreakdown: 'Category Breakdown',
  categoryBreakdownSub: 'Targets, achievements and commission contribution',
  myCommission: 'My Commission',
  tableCategory: 'Category',
  tableTarget: 'Target',
  tableAchieved: 'Achieved',
  tableCommission: 'Commission',
  garments: 'Garments',
  unstitched: 'Unstitched',
  accessories: 'Accessories',
  slipBoundIncentive: 'Slip Bound Incentive',
  slipBoundIncentiveSub: 'Invoice based incentive records',
  incentiveDate: 'Date',
  incentiveSlab: 'Slab',
  incentiveInvoice: 'Invoice',
  incentiveSalesId: 'Sales ID',
  incentiveNetSale: 'Net Sale',
  incentiveAmount: 'Incentive',
  profileHeader: 'Profile',
  updateProfile: 'Update Profile',
  save: 'Save',
  cancel: 'Cancel',
  noNotifications: 'No notifications available',
  profileInformation: 'PROFILE INFORMATION',
  readOnly: 'Read only',
  fullName: 'Full Name',
  branchName: 'Branch',
  designation: 'Designation',
  profileBranch: 'Branch Name',
  region: 'Region',
  seniorSalesStaff: 'Senior Sales Staff',
  accountSettings: 'ACCOUNT SETTINGS',
  changePassword: 'Change Password',
  changePasswordSubtitle: 'Update your password securely',
  staffComparisonHeader: 'Staff Comparison',
  weekly: 'Weekly',
  monthly: 'Monthly',
  saleemYou: 'Saleem (You)',
  achievedSuffix: 'Achieved',
  achieveTarget: 'Achieve Target',
  rank: 'Rank',
  name: 'Name',
  target: 'Target',
  conversionRate: 'Conversion Rate',
  conversions: 'Conversions',
  footfallVsInvoicesPerformance: 'Footfall vs invoices performance',
  dateRange: 'Date Range',
  from: 'From',
  to: 'To',
  peakLabel: 'Peak: 06:00 - 58%',
  footfall: 'Footfall',
  traffic: 'Traffic',
  trafficInv: 'TRAFFIC/INV',
  conversionPercent: 'CONV %',
  invoices: 'Invoices',
  TargetAssignment: 'Target Assignment',
  TotalStaff: 'Total Staff',
  Completed: 'Completed',
  Pending: 'Pending',
  SurveyReport: 'Survey Report',
  Detailed: 'Detailed responses & analytics',
  totalResponses: 'Total Responses',
  totalCountSeparator: ' / ',
  responseRatePrefix: '↗ ',
  responseRateSuffix: ' response rate',
  monthlyTargetCalculator: 'Monthly Target Calculator',
  categoryWiseDistribution: 'Category-wise distribution',
  categoryHeader: 'CATEGORY',
  targetHeader: 'TARGET',
  assignedHeader: 'ASSIGNED',
  leftHeader: 'LEFT',
  totalAssigned: 'Total Assigned',
  branchTargets: 'Branch Targets',
  tapToViewTargets: 'Tap to view targets',
  total: 'Total',
  tableName: 'NAME',
  tableGarments: 'GARMENTS',
  tableUnstitched: 'UNSTITCHED',
  tableAccessShort: 'ACCESS.',
  staffMembers: count => `${count} staff members`,
  categoryPerformance: 'Category Performance',
  staffDetailsHeader: 'Staff Details',
  staffDetailSelectStaff:
    'Please select a staff member from Staff Comparison to view details.',
  staffDetailMissingId:
    'Staff ID is missing. Backend should send staff_id in staff comparison API.',
  dhaBranch: 'DHA Branch',
  achievedLabel: 'Achieved',
  remainingLabel: 'Remaining',
  contribution: 'Contribution',
  liveStatus: 'Live Status',
  branchMonthlyTarget: 'Branch Monthly Target',
  myBranchTargets: 'My Branch Targets',
  myBranchPerformance: 'My Branch Performance',
  achievement: 'Achievement',
  unitsLabel: 'Units',
  done: 'Done',
  next: 'Next',
  categoryPerformanceSuffix: category => `${category} Performance`,
};
